%Set intial date for the simualtion
Settle = datenum('31-12-2020');
%Provide the starting term structure
mrktMaturities = [0.5,1,2,3,5,7,10,20,30];
mrktYields = [-0.00257, -0.00105,-0.00115,0.0090,0.0115,0.0213,0.0352,0.0377,0.0411]; 
%Provide the maturities you want for the simulated term strucutres
CurveDates = daysadd(Settle,360*mrktMaturities,1);
%Create the object IRDataCurve with the previous variables
irdc = IRDataCurve('Zero',Settle,CurveDates,mrktYields);
%Fit the Hull-White Vasicek 1 factor model to create the path 
obj = HullWhite1F(irdc, params.kappa, params.eta);
%Simulate scenarios, the result will be a 3D matrix n,m,j.
SimPaths = simTermStructs(obj, numel(mrktMaturities),'nTrials',10);

%Code for term sructures plot
plot(mrktMaturities, SimPaths(:,:,1))
function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 09-Apr-2021 11:50:54

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'LineWidth',7);

box(axes1,'on');
hold(axes1,'off');
% Create textarrow
annotation(figure1,'textarrow',[0.344802342606149 0.493411420204978],...
    [0.456757296466974 0.253456221198157]);

% Create textbox
annotation(figure1,'textbox',...
    [0.501 0.218125960061444 0.112469985358712 0.0476190476190476],...
    'String',{'Starting Term Structure'},...
    'FitBoxToText','off');
end


