%---------VASICEK PARAMETERS OPTIMIZATION AND YIELD CURVE COMPARISON------------

function params=vasicekOptim(mrktMaturities, mrktYields)
%We run the function YieldCurveFitVasicek that will optimize the parameters
%the function is defined below
params = YieldCurveFitVasicek(mrktMaturities, mrktYields);

%Let us now calculate bond prices estimated with Vasicek
vasicek_bondPrices = UnitDiscBondVasicek(mrktMaturities,params);
real_bondPrices = exp(-mrktYields.*mrktMaturities);
%To conclude let's calculate the yields coming out from Vasicek model
r0	= CalcDiscountBondYield(1/365,UnitDiscBondVasicek(1/365,params));
vasicek_yields	= CalcDiscountBondYield(mrktMaturities,vasicek_bondPrices);
%Eventually we plot the Zero curve for yields comparison
%We first define the matrix of the yields
Y = [vasicek_yields; mrktYields];
%We have already defined the function for plot creation below
% createfigureVasicekYield(mrktMaturities, Y);

s=2;



%This function generates the plot for the Zero curve
function createfigureVasicekYield(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Oct-2020 22:24:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerFaceColor','auto','Marker','square');
set(plot1(1),'DisplayName','Vasicek estimated yield curve');
set(plot1(2),'DisplayName','Market yield curve');

% Create ylabel
ylabel({'Yields'});

% Create xlabel
xlabel({'Maturities'});

% Create title
title({'Zero Curves'});

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','northwest');
end

end